templates:
  '-':
    enabled: true
    template: 'Input: {{input}}

      Context: {{context_folder}}'
  diagnose:
    enabled: true
    template: 'Problem: {{input}}

      Analyzing: {{context_folder}}

      '
  review-code:
    enabled: true
    template: 'Review: {{input}}

      Context: {{context_folder}}

      Focus File: {{focus_file}}

      '
  test-agent:
    enabled: true
    template: 'Input: {{input}}

      Context: {{context_folder}}'
  test-command:
    enabled: true
    template: 'Valid template: {{input}}'
  ux-ui-improver:
    enabled: true
    template: 'Request: {{input}}

      Project: {{context_folder}}

      Current File: {{focus_file}}

      '
  verify-python:
    enabled: true
    template: 'File: {{input}}

      Context: {{context_folder}}

      Focus: {{focus_file}}

      '
version: '2.0'
